export const CREATE_EVENT_ITEM_PENDING = 'CREATE_EVENT_ITEM_PENDING';
export const CREATE_EVENT_ITEM_REJECTED = 'CREATE_EVENT_ITEM_REJECTED';
export const CREATE_EVENT_ITEM_FULFILLED = 'CREATE_EVENT_ITEM_FULFILLED';
