export const DELETE_EVENT_ITEM_PENDING = 'DELETE_EVENT_ITEM_PENDING';
export const DELETE_EVENT_ITEM_FULFILLED = 'DELETE_EVENT_ITEM_FULFILLED';
export const DELETE_EVENT_ITEM_REJECTED = 'DELETE_EVENT_ITEM_REJECTED';
