export const EDIT_EVENT_ITEM_PENDING = 'EDIT_EVENT_ITEM_PENDING';
export const EDIT_EVENT_ITEM_FULFILLED = 'EDIT_EVENT_ITEM_FULFILLED';
export const EDIT_EVENT_ITEM_REJECTED = 'EDIT_EVENT_ITEM_REJECTED';
