export const GET_EVENTS_LIST_PENDING = 'GET_EVENTS_LIST_PENDING';
export const GET_EVENTS_LIST_REJECTED = 'GET_EVENTS_LIST_REJECTED';
export const GET_EVENTS_LIST_FULFILLED = 'GET_EVENTS_LIST_FULFILLED';

export const CLEAR_CURRENT_EVENT_ITEM = 'CLEAR_CURRENT_EVENT_ITEM';
export const GET_EVENT_ITEM_BY_ID = 'GET_EVENT_ITEM_BY_ID';
