export const GET_CURRENT_DATE_NOW = 'GET_CURRENT_DATE_NOW';
export const GET_CURRENT_DATE = 'GET_CURRENT_DATE';

export const ADD_EVENT_PENDING = 'ADD_EVENT_PENDING';
export const ADD_EVENT_REJECTED = 'ADD_EVENT_REJECTED';
export const ADD_EVENT_FULFILLED = 'ADD_EVENT_FULFILLED';

export const ADD_SAVED_EVENTS_LIST_TO_STORAGE = 'ADD_SAVED_EVENTS_LIST_TO_STORAGE';

export const SHOW_MESSAGE_MODAL = 'SHOW_MESSAGE_MODAL';
export const HIDE_MESSAGE_MODAL = 'HIDE_MESSAGE_MODAL';

export const GET_EVENT_ITEM_BY_ID = 'GET_EVENT_ITEM_BY_ID';

export const EDIT_EVENT_ITEM_PENDING = 'EDIT_EVENT_ITEM_PENDING';
export const EDIT_EVENT_ITEM_FULFILLED = 'EDIT_EVENT_ITEM_FULFILLED';
export const EDIT_EVENT_ITEM_REJECTED = 'EDIT_EVENT_ITEM_REJECTED';

export const CLEAR_CURRENT_EVENT_ITEM = 'CLEAR_CURRENT_EVENT_ITEM';

export const SORT_EVENTS_LIST = 'SORT_EVENTS_LIST';

export const GET_EVENTS_LIST_PENDING = 'GET_EVENTS_LIST_PENDING';
export const GET_EVENTS_LIST_REJECTED = 'GET_EVENTS_LIST_REJECTED';
export const GET_EVENTS_LIST_FULFILLED = 'GET_EVENTS_LIST_FULFILLED';

export const DELETE_EVENT_ITEM_PENDING = 'DELETE_EVENT_ITEM_PENDING';
export const DELETE_EVENT_ITEM_FULFILLED = 'DELETE_EVENT_ITEM_FULFILLED';
export const DELETE_EVENT_ITEM_REJECTED = 'DELETE_EVENT_ITEM_REJECTED';

export const SAVE_EVENT_CHANGES_PENDING = 'SAVE_EVENT_CHANGES_PENDING';
export const SAVE_EVENT_CHANGES_FULFILLED = 'SAVE_EVENT_CHANGES_FULFILLED';
export const SAVE_EVENT_CHANGES_REJECTED = 'SAVE_EVENT_CHANGES_REJECTED';
