export const GET_CURRENT_DATE_NOW = 'GET_CURRENT_DATE_NOW';
export const GET_CURRENT_DATE = 'GET_CURRENT_DATE';
export const ADD_EVENT_PENDING = 'ADD_EVENT_PENDING';
export const ADD_EVENT_REJECTED = 'ADD_EVENT_REJECTED';
export const ADD_EVENT_FULFILLED = 'ADD_EVENT_FULFILLED';
export const ADD_SAVED_EVENTS_LIST_TO_STORAGE = 'ADD_SAVED_EVENTS_LIST_TO_STORAGE';
export const SHOW_MESSAGE_MODAL = 'SHOW_MESSAGE_MODAL';
export const HIDE_MESSAGE_MODAL = 'HIDE_MESSAGE_MODAL';
