const timeConstants = {
  COUNT_MONTHS_IN_YEAR: 12,
  COUNT_HOURS_IN_DAY: 24,
  YEAR_STRING_LENGTH: 4,
  MONTH_STRING_LENGTH: 2,
  DAY_STRING_LENGTH: 2,
  START_DAY_TIME: '00:00',
  END_DAY_TIME: '23:59',
  ONE_SECOND: 1000,
  TWO_SECONDS: 2000
};

export default timeConstants;
